# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coalay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'gRPC-Swift', '~> 1.0.0-alpha.19'

  # Pods for coalay

  target 'coalayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coalayUITests' do
    # Pods for testing
  end

end
